### ISSUE TITLE
Data Flow Diagram: Cart

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#12]
- [x] Design
- [ ] Approval

**Comment by Spawbreaker** [comment]
First draft of the Cart Data Flow Diagram.

![Cart Data Flow Diagram](https://user-images.githubusercontent.com/37517471/62898754-e4afbd80-bd1b-11e9-992d-8025aab7d388.png)

As any user, even guests (Who should get a temporary user account) must have a cart assigned to them, and you can only work on your own cart, I don't think any of the methods can really fail, thus, I didn't feel the need to add any fail-case situations in the diagram.

**Comment by Spawbreaker** [comment]
Just as I posted it (again) I found an error case that should be validated.

- Added case where no user has an auth token that matches the client. (Bad Auth)

![Cart Data Flow Diagram (1)](https://user-images.githubusercontent.com/37517471/62899323-212fe900-bd1d-11e9-940c-fbee1654755c.png)

**Comment by pablorich** [comment]
I think the user data is saved in the back-end if you have a session, so making a query to find a user might not be necessary.

**Comment by Spawbreaker** [comment]
I just read up on this, the session (JWT) encrypts the user's data and can be broken down into a user again, but maybe it would be safe to see if user STILL exists?  I feel we should discuss this.

**Comment by Spawbreaker** [comment]
I researched JWT further, I feel this should be right this time.

![wsd - Cart](https://user-images.githubusercontent.com/37517471/63275125-9a23c900-c266-11e9-99b8-77a7f570d544.png)

**Comment by pablorich** [comment]
Everything fine.
Do we need to define the case when a user clicks on checkout?(just load the checkout page) If not, then I think this is done

**Comment by Spawbreaker** [comment]
It shouldn't be necessary, so I'm closing this issue now!
