### ISSUE TITLE
Endpoint Cart bug

### ISSUE THREAD

**Issue by pablorich** [IntersysConsulting/mdc_team_b_back#122]
Problem:
Cart get throws internal server error
Cart get throws empty object in new carts

Expected results:
Cart get resolving.
New carts should throw {[]} instead of {}

Steps to reproduce:
Create guest token
Call /cart get -> returns 200 with data = {}
Call /cart put -> success
Call /cart get -> internal server error
console log:
![image](https://user-images.githubusercontent.com/15503226/66497780-9e0fe280-ea82-11e9-96af-d6061ea8f8e0.png)

**Comment by Spawbreaker** [comment]
Culprit was not the endpoint, but a mistake I already fixed, but didn't look at in the database.

![image](https://user-images.githubusercontent.com/37517471/66498649-014e4480-ea84-11e9-8ce5-287692b0de0b.png)

The product `5d8b8697257666a7b8608892` was faulty having a wrong value for "price" which the dump ended up voiding, as it wasn't type appropiate, thus, the object did not have a "price" index.  Fixed the product, it should work as expected with nothing else. Can you confirm this so I can close this issue?

**Comment by pablorich** [comment]
Confirmed
