### ISSUE TITLE
Data Flow Diagram: Storefront

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#2]
- [x] Design
- [ ] Approval

**Comment by pablorich** [comment]
![Storefront](https://user-images.githubusercontent.com/15503226/62792069-16aeee80-ba94-11e9-953a-8020566dcd18.png)
No se si falten cosas por considerar en este diagrama.
Considero que hacer el filtrado y el sorting en el front es la mejor opción para no tener que recargar la página, que piensan?

**Comment by Spawbreaker** [comment]
Hey Pablo!

Same thing as in [the other task you took](https://github.com/IntersysConsulting/mdc_team_b_back/issues/4#issuecomment-520060197).

Read: I'm not sure if this is important on the dataflow diagram, but maybe we should ask for an 'n' number of products since the 'm' position to be sent so that the app doesn't slow down processing potential thousands of items in a single query. Maybe irrelevant due to the size of the project, but I believe we should address this possibility.

Other than that point this one looks great, as soon as we get that resolved I'll close this issue. Great job!

**Comment by pablorich** [comment]
I think we should address this concern with the team, because the data flow as it is in this diagram works very good when you don't have a lot of products and allows us to sort and filter in the front end.
If we change it to request items in chunks we need to filter and sort in every query, moving the strain from the front-end to the database.

**Comment by pablorich** [comment]
Considering API pagination.
Leaving this for an hour before closing the issue.
![Storefront](https://user-images.githubusercontent.com/15503226/62889678-782ac380-bd07-11e9-9c91-7bb745e5c841.png)

**Comment by pablorich** [comment]
Added stuff that might help later
![Storefront (1)](https://user-images.githubusercontent.com/15503226/63179346-80d60f00-c011-11e9-8d0d-ae7f71b17383.png)
