### ISSUE TITLE
API design: Order endpoints

### ISSUE THREAD

**Issue by AnaSandoval-Intersys** [IntersysConsulting/mdc_team_b_back#25]
Design and document the endpoints needed for orders.

- [ ] POST
- [ ] GET
- [ ] DELETE
- [ ] PUT

**Comment by Spawbreaker** [comment]
Hey Pablo :D Totally not wrong person now. 

I would change the /any/orders/ to just /orders/ and merge it with /user/orders/, they're publicly accessed.
- POST
  - If the logic behind /any and /user is the same I would change the parameters it requests to optional parameters. Remember Guests are also in our Customer table, they **do** have a user_id and an auth token. 
  - I would change the parameters to:
    - An auth-token (required) (Handled by jwt) to get the user id, with it we can also fetch the cart information and with that we can get the item IDs to query the DB for the actual items.
    - Billing Information
    - Shipping Information

Don´t worry about the guest giving us their email! The front end should PUT on /customers/ their e-mail, phone, first name and last name before POSTing this request ;) 

- GET 
  - Sending the user ID would be dangerous, as someone with the right ID could see delicate information (shipping/billing address) of a user. It's better to request an Auth-token, which we can decrypt into the user's ID. 
  - I hadn't thought of sort/filter/pagination for this, but it totally makes sense! Good job. 
  - Don't worry, if a guest does this it would just return an empty json / the orders they made THIS session. So it's failproof.

Admin
  - PUT
    - I would change the help to "ID of the new status".
  - GET
    - This one's perfect
  - DELETE
    - I don't know if I would consider it missing. It is not a very common method, in fact, this information should almost never be deleted. But maybe it would be good to have it? Up to you, this one wouldn't see use anyway under normal circumstances. 

I think this was mostly discussed today, and I hadn't super-noticed you merged to master, lol.
