### ISSUE TITLE
Data Flow Diagram: Product Management

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#4]
- [x] Design
- [ ] Address admin token order
- [ ] Approval

**Comment by pablorich** [comment]
![Product Management](https://user-images.githubusercontent.com/15503226/62800860-0f92db00-baaa-11e9-89a5-9f46c0ba291f.png)
Este es bastante grande, chequenlo bien

**Comment by Spawbreaker** [comment]
Hi Pablo! This was a big chunk of info!

Overall: I believe this is a great work overall, but the admin token should be validated before querying the database so that the database doesn't have to roll back if the token is invalid. 

Read: I'm _not sure_ if this is important on the dataflow diagram, but maybe we should ask for an '_n_' number of products since the '_m_' position to be sent so that the app doesn't slow down processing potential thousands of items in a single query. Maybe irrelevant due to the size of the project, but I believe we should address this possibility.

**Comment by pablorich** [comment]
I think there was a misunderstanding with the admin token validation part; What I meant was to validate the authenticity with the admin session token and the key you get from the database.
Added loading the products in chunks of 20 as well as sorting and filtering options. 
![Product Management](https://user-images.githubusercontent.com/15503226/62878850-8bca3000-bcef-11e9-9a90-765f44200fe1.png)

**Comment by pablorich** [comment]
Fixed token validation process flow.
Querys for next 20 items is probably going to be done with API pagination.
Leaving this for an hour before marking issue as done.
![Product Management](https://user-images.githubusercontent.com/15503226/62889012-1a49ac00-bd06-11e9-82b8-4081ee501ca5.png)
