### ISSUE TITLE
Data Flow Diagram: Checkout

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#5]
- [x] Design
- [ ] Approval

**Comment by Spawbreaker** [comment]
Hey Pablo!
I feel a bit mean with how many corrections I made on this one, I'm sorry. 

- We don't return our client's credit card info. If at all, it would be their browser auto-filling it. We are **only** required to save their shipping and billing info. We don't even know if we are going to be allowing credit card payments yet. 
- You can just request the user´s cart information, it's an order, and it should contain the user's shipping-billing-cart info.
- Instead of "order resume" it would be "summary" (or résumé, in french, though summary is much better here). It's a fake-friend from spanish-english. 
- Some typos of "proceed" where it's spelled as "procced" or "procedes" 
- Check capitalization mistakes.
- We don't need the client to send "new info". I would leave the field blank and in case they fill it in with info we don't have we could then either prompt them to update their info (Add or replace, we should discuss this) or just do it automatically. 
- Are you sure [modal](https://www.vocabulary.com/dictionary/modal) is being used properly? 
- Instead of "correctly" consider using "successfully", as _something incorrect may still be successful_.
- I haven't used any payment providers as a developer, I don't know how it would be handled. It would be wise to approach our ambassador about it. 
- Placing an order should send an email to the merchant and to the customer. (Maybe rename user to customer?) (1.0 Release) 
- Order should be state-updated after poking the Payment Service to "Processing payment", not "saved", as it's been stored in the database since the creation of the cart.

**Comment by pablorich** [comment]
- I agree we don't return the credit card info but we do return some of it just so the customers identifies if it's the correct card. I'm gonna leave that part of the diagram the same for now.

- Fixed (hopefully) all the typos and capitalized words correctly.

- I followed your advice in the words that might be better to use.

- I don't think the cart should be treated as an order, and given that, it shouldn't contain the user's shipping-billing info.

- I changed the diagram so when the customer confirms the order, we create the order, but it doesn't process the payment until an admin takes the money from his "orders" menu

![Checkout (3)](https://user-images.githubusercontent.com/15503226/63108449-80c00b80-bf4c-11e9-9f87-b6ab294fd499.png)

**Comment by pablorich** [comment]
Please read the notes where I assume how some stuff works.
![Checkout (5)](https://user-images.githubusercontent.com/15503226/63191866-411e2000-c02f-11e9-9cb7-7a780dadba60.png)

I also made a diagram for the data flow for a guest
![Checkout for guests](https://user-images.githubusercontent.com/15503226/63191957-7a569000-c02f-11e9-9894-d710a9214381.png)

**Comment by Spawbreaker** [comment]
I like this! I feel the guest view _could_ be unnecessary but it is better to have some extra than to have some missing. 

This should be ready to close whenever you want!
