### ISSUE TITLE
Data Flow Diagram: Sign Up

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#6]
- [x] Design
- [x] Approval

**Comment by AnaSandoval-Intersys** [comment]
Diagrama de secuencia propuesto:
![Sign Up Sequence 1](https://user-images.githubusercontent.com/53873395/62797832-4f55c480-baa2-11e9-9416-03c91d612b29.png)

O. en caso de que decidieramos implementar correos para sign-up:
![Sign Up Sequence](https://user-images.githubusercontent.com/53873395/62797865-6a283900-baa2-11e9-94bf-37cc4bfee1ee.png)

**Comment by AnaSandoval-Intersys** [comment]
Proposed diagram:
![Sign Up Sequence](https://user-images.githubusercontent.com/53873395/62803882-47e9e780-bab1-11e9-8c16-408de36fc0d2.png)

If you have any feedback please leave me a comment.

**Comment by Spawbreaker** [comment]
This is a great job Ana! I'll leave the issue open for about an hour for anyone else to give in feedback. If nobody objects to it I'll proceed to integrate this into the files and close this issue.

**Comment by AnaSandoval-Intersys** [comment]
Same diagram as above, just with a new format so all of them have the same style.

![Sign Up Sequence](https://user-images.githubusercontent.com/53873395/62890195-8fb67c00-bd08-11e9-83de-1244897ff635.png)
