### ISSUE TITLE
Data Flow Diagram: Staff

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#8]
- [x] Design
- [x] Approval

**Comment by AnaSandoval-Intersys** [comment]
I'm adding the diagram for admin management (staff)
![Admin Management Sequence](https://user-images.githubusercontent.com/53873395/62890089-53831b80-bd08-11e9-9f04-6817a5e00955.png)

¿Any thoughts?

**Comment by Spawbreaker** [comment]
Hey Ana!  Since we are dealing with admin endpoints we should always double check for admin's session token before sending any information, we don't want a random user getting our admins' emails, addresses and other information. And maybe double check (or just move the validation to the backend?) the user's permissions when adding, deleting, or updating a

Errors that maybe should be accounted for
- A 403 error In case we get insufficient permissions .
- A 404 error in case an update or delete is done in an admin that does not exist. 
- A 409 error in case an admin tries to delete themselves / tries to delete the last admin (If you can't delete the current admin you can't delete the last admin, so I guess that's a good enough validation)
- A 410 error in case an update is executed on an admin that was deleted (May be wise to just keep a 404. May be hard to catch when a 404 is a 410)

**Comment by AnaSandoval-Intersys** [comment]
Thanks! Working on the double checking admin's session & permissions part now, that's a good observation.
Regarding the errors, I'm handling them just as error response/error message for the diagram; same for the validation of an admin not deleting themselves or the last admin (the "validates admin can be deleted" part) would it be important to indicate every single one separately in the diagram?

**Comment by AnaSandoval-Intersys** [comment]
New, bigger version: 

![Admin Management Sequence](https://user-images.githubusercontent.com/53873395/62959990-52f98c00-bdbf-11e9-96b8-1a6616faa9e7.png)

Admin's session is now validated for each case, thank you!
As for the errors, For the sake of the length of the diagram I'm using a general "Error response"/"Error message". Once we move forward on the project we can work on catching each one separately :)

**Comment by AnaSandoval-Intersys** [comment]
Some changes for password update.

![Admin Management Sequence 2 0](https://user-images.githubusercontent.com/53873395/63289292-63f54200-c284-11e9-8821-d1983e4a82c7.png)
