### ISSUE TITLE
Data Flow Diagram: Order Management

### ISSUE THREAD

**Issue by Spawbreaker** [IntersysConsulting/mdc_team_b_back#9]
- [x] Design
- [ ] Approval

**Comment by CrhistianH** [comment]
![E-Commerce Order Management](https://user-images.githubusercontent.com/30354352/62901505-95b95680-bd22-11e9-8f4b-8afc98d1372b.png)

**Comment by Spawbreaker** [comment]
Maybe it's just me but I would consider changing the last alt case's title to a more general case of error or include other various errors that can happen. Since it's a minor change I leave it to your discretion.

**Comment by CrhistianH** [comment]
![E-Commerce Order Management](https://user-images.githubusercontent.com/30354352/62956908-61dd4000-bdb9-11e9-89f7-ff13b1b5f524.png)
